<a href="https://colab.research.google.com/github/rfaoktvian/Chronic-Kidney-Disease/blob/main/Vidio_Case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### IMPORT LIBRARY

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

### LOAD DATA

In [ ]:
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Job Seek/Vidio/vidio_dataset.csv'
df = pd.read_csv(path,on_bad_lines='skip',engine='python')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### DATA UNDERSTANDING

In [ ]:
df.head()

,hash_content_id,hash_play_id,hash_visit_id,hash_watcher_id,hash_film_id,hash_event_id,is_login,playback_location,platform,play_time,...,app_version,city,play_duration,content_type,stream_type,title,category_name,film_title,season_name,genre_name
0,003f6dad4ab48a4e39ea262b19e3b42a4b53c2175078b3...,515dd4d7af23ae9ef5a2455bc97ee765fe86224ebaca71...,ed8d97adbba52562575973553003d9a13b103bc4693a6c...,3ba64f349972d4c7c05eb08e6b91db156a91af555ded6f...,NaN,175c473e6bbf67c337bdbd14c9dbdf01c627bfe5af17c1...,True,direct,tv-android,2020-02-15T12:07:00.000Z,...,1.11.0 (50),NaN,1263,vod,NaN,FTV SCTV - Kecubit Cinta Sahabat Chantiq,Movies,NaN,NaN,NaN
1,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,047f7b21bcb1a57119229958b11abe364ce1a279f8ae00...,88a404df574ba3c637bb99e94a2e51b16114f5da6f99cd...,36fd7b04f88ef3d6f16326ae4a39fcf2e4b1dec052919c...,NaN,6f8d1372d0128e141c7ef87649d9ec46328d327c2a21d4...,False,embed,web-mobile,2020-02-14T18:37:52.000Z,...,NaN,NaN,0,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN
2,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,2623b2970635a15f1cf12bf9aa1e4d545135593e6a860c...,24abc04f114c9cb0c2087568093a909f04b3a567041fff...,4906987a7a6c3e27895e1adfd200d38e4f4fd87eb9ce96...,NaN,e73122fb4da263f0825c2ae5ac5c5a18da3a45c44b49e6...,False,embed,web-mobile,2020-02-15T11:58:24.000Z,...,NaN,NaN,8,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN
3,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,4850defe8308149c097ff7adfe6fbdab1385a4d2ea7038...,f1279ae82e3c45f7591ad8e43f69a87d7444bf1c4b70b1...,adaf91b743f2f1d7b93819b22c016ca700182bd1a5b854...,NaN,1e8d1186fbc7677e10aa4a512f20ec01348e3e7f9e4cb7...,False,embed,web-mobile,2020-02-15T06:36:08.000Z,...,NaN,NaN,53,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN
4,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,ae0cb715407a6694fb052f4d25b9c87e97ab6ccafdb388...,151db218c9cbad4d9fa1b1196fd998a63a8314698580a6...,15689b6aebb6b896c7fdadb516c9754a34a2fcfb772dc3...,NaN,210d2693895749e26711ee890ef41c461994ce91a673aa...,False,embed,web-mobile,2020-02-15T01:53:03.000Z,...,NaN,NaN,53,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN

In [ ]:
df.shape

(731622, 41)

In [ ]:
df.describe()

       average_bitrate   total_bytes  buffer_duration  city  play_duration
count    697042.000000  7.316220e+05     7.316220e+05   0.0  731622.000000
mean     199642.859208  8.154527e+07     4.131891e+02   NaN     438.022129
std      141318.399261  5.174427e+08     7.242157e+04   NaN    1662.884277
min         144.000000  0.000000e+00    -4.639000e+00   NaN       0.000000
25%         633.000000  7.500000e+02     1.400000e-02   NaN       3.000000
50%      300000.000000  5.250000e+05     1.000000e+00   NaN      40.000000
75%      300000.000000  1.125000e+07     6.000000e+00   NaN     120.000000
max      300000.000000  5.065312e+10     6.117224e+07   NaN  135075.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731622 entries, 0 to 731621
Data columns (total 41 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   hash_content_id    731622 non-null  object
 1   hash_play_id       731622 non-null  object
 2   hash_visit_id      731622 non-null  object
 3   hash_watcher_id    731622 non-null  object
 4   hash_film_id       40454 non-null   object
 5   hash_event_id      731622 non-null  object
 6   is_login           731622 non-null  bool
 7   playback_location  731622 non-null  object
 8   platform           731622 non-null  object
 9   play_time          731622 non-null  object
 10  end_time           731622 non-null  object
 11  referrer           691287 non-null  object
 12  average_bitrate    697042 non-null  float64
 13  bitrate_range      731622 non-null  object
 14  total_bytes        731622 non-null  int64
 15  buffer_duration    731622 non-null  float64
 16  referrer_group     731622 non-null  object
 17  completed          462166 non-null  object
 18  utm_source         760 non-null     object
 19  utm_medium         757 non-null     object
 20  utm_campaign       311 non-null     object
 21  player_name        708835 non-null  object
 22  has_ad             731622 non-null  bool
 23  flash_version      490374 non-null  object
 24  os_name            497944 non-null  object
 25  os_version         728912 non-null  object
 26  browser_name       498583 non-null  object
 27  browser_version    481963 non-null  object
 28  app_name           731622 non-null  object
 29  autoplay           462020 non-null  object
 30  is_premium         731622 non-null  bool
 31  app_version        239998 non-null  object
 32  city               0 non-null       float64
 33  play_duration      731622 non-null  int64
 34  content_type       731622 non-null  object
 35  stream_type        269456 non-null  object
 36  title              731622 non-null  object
 37  category_name      462166 non-null  object
 38  film_title         40441 non-null   object
 39  season_name        40454 non-null   object
 40  genre_name         35960 non-null   object
dtypes: bool(3), float64(3), int64(2), object(33)
memory usage: 214.2+ MB

In [ ]:
missing = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': round((df.isnull().sum()/len(df))*100,2)
})

display(
    missing.sort_values(
        by='Missing Percentage',
        ascending=False
    )
)

                   Missing Count  Missing Percentage
city                      731622              100.00
utm_campaign              731311               99.96
utm_medium                730865               99.90
utm_source                730862               99.90
genre_name                695662               95.08
film_title                691181               94.47
season_name               691168               94.47
hash_film_id              691168               94.47
app_version               491624               67.20
stream_type               462166               63.17
autoplay                  269602               36.85
category_name             269456               36.83
completed                 269456               36.83
browser_version           249659               34.12
flash_version             241248               32.97
os_name                   233678               31.94
browser_name              233039               31.85
referrer                   40335                5.51
average_bitrate            34580                4.73
player_name                22787                3.11
os_version                  2710                0.37
hash_watcher_id                0                0.00
hash_visit_id                  0                0.00
hash_play_id                   0                0.00
hash_content_id                0                0.00
platform                       0                0.00
playback_location              0                0.00
is_login                       0                0.00
hash_event_id                  0                0.00
bitrate_range                  0                0.00
referrer_group                 0                0.00
buffer_duration                0                0.00
play_time                      0                0.00
has_ad                         0                0.00
total_bytes                    0                0.00
end_time                       0                0.00
app_name                       0                0.00
is_premium                     0                0.00
title                          0                0.00
play_duration                  0                0.00
content_type                   0                0.00

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique().sort_values()

city                      0
is_login                  2
has_ad                    2
playback_location         2
is_premium                2
autoplay                  2
stream_type               2
completed                 2
app_name                  3
content_type              3
bitrate_range             3
player_name               3
platform                  7
utm_medium                8
utm_source               12
category_name            15
os_name                  16
utm_campaign             16
referrer_group           17
browser_name             51
flash_version            60
season_name             153
app_version             154
os_version              269
genre_name              528
average_bitrate         638
film_title              665
hash_film_id            668
browser_version        1024
play_duration          7157
total_bytes           10506
title                 32332
hash_content_id       33561
buffer_duration       59930
referrer             104445
end_time             529229
play_time            530604
hash_watcher_id      634585
hash_visit_id        716887
hash_play_id         731570
hash_event_id        731584
dtype: int64

In [ ]:
cols_cek = [
    'platform', 'content_type', 'playback_location',
    'referrer_group', 'bitrate_range', 'stream_type',
    'os_name', 'app_name', 'player_name'
]

for col in cols_cek:
    print(f"\n── {col} ──")
    print(df[col].value_counts(dropna=False).to_string())

── platform ──
platform
web-mobile     420109
app-android    179187
web-desktop     70265
tv-android      41352
app-ios         12500
tv-tizen         7041
tv-webos         1168

── content_type ──
content_type
vod              459321
livestreaming    269456
catchup            2845

── playback_location ──
playback_location
embed     370030
direct    361592

── referrer_group ──
referrer_group
others       244991
kapanlagi    108243
internal      77613
liputan6      72291
merdeka       71837
dream         44887
empty         40335
google        23877
bola          20856
bolanet       17049
otosia         4045
fimela         3851
emtek           785
facebook        587
telkomsel       295
twitter          79
brilio            1

── bitrate_range ──
bitrate_range
200-500    463359
0-200      233683
unknown     34580

── stream_type ──
stream_type
NaN            462166
TvStream       264990
EventStream      4466

── os_name ──
os_name
Android           394389
NaN               233678
Windows            65228
iOS                26199
REL                 7570
Mac OS X            2907
Linux               1061
Tizen                229
Ubuntu               161
Other                 99
Chrome OS             71
BlackBerry OS         17
Windows Phone          8
Firefox OS             2
Red Hat                1
Fedora                 1
Symbian^3 Anna         1

── app_name ──
app_name
vidio       731480
liputan6        81
bola            61

── player_name ──
player_name
videojs            490374
KmkExoVideoView    218456
NaN                 22787
kmkexoplayer            5

### DATA PREPROCESSING

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean.head()

,hash_content_id,hash_play_id,hash_visit_id,hash_watcher_id,hash_film_id,hash_event_id,is_login,playback_location,platform,play_time,...,app_version,city,play_duration,content_type,stream_type,title,category_name,film_title,season_name,genre_name
0,003f6dad4ab48a4e39ea262b19e3b42a4b53c2175078b3...,515dd4d7af23ae9ef5a2455bc97ee765fe86224ebaca71...,ed8d97adbba52562575973553003d9a13b103bc4693a6c...,3ba64f349972d4c7c05eb08e6b91db156a91af555ded6f...,NaN,175c473e6bbf67c337bdbd14c9dbdf01c627bfe5af17c1...,True,direct,tv-android,2020-02-15T12:07:00.000Z,...,1.11.0 (50),NaN,1263,vod,NaN,FTV SCTV - Kecubit Cinta Sahabat Chantiq,Movies,NaN,NaN,NaN
1,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,047f7b21bcb1a57119229958b11abe364ce1a279f8ae00...,88a404df574ba3c637bb99e94a2e51b16114f5da6f99cd...,36fd7b04f88ef3d6f16326ae4a39fcf2e4b1dec052919c...,NaN,6f8d1372d0128e141c7ef87649d9ec46328d327c2a21d4...,False,embed,web-mobile,2020-02-14T18:37:52.000Z,...,NaN,NaN,0,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN
2,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,2623b2970635a15f1cf12bf9aa1e4d545135593e6a860c...,24abc04f114c9cb0c2087568093a909f04b3a567041fff...,4906987a7a6c3e27895e1adfd200d38e4f4fd87eb9ce96...,NaN,e73122fb4da263f0825c2ae5ac5c5a18da3a45c44b49e6...,False,embed,web-mobile,2020-02-15T11:58:24.000Z,...,NaN,NaN,8,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN
3,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,4850defe8308149c097ff7adfe6fbdab1385a4d2ea7038...,f1279ae82e3c45f7591ad8e43f69a87d7444bf1c4b70b1...,adaf91b743f2f1d7b93819b22c016ca700182bd1a5b854...,NaN,1e8d1186fbc7677e10aa4a512f20ec01348e3e7f9e4cb7...,False,embed,web-mobile,2020-02-15T06:36:08.000Z,...,NaN,NaN,53,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN
4,0079c67ae8c7f6cbd44768f1988196c137326f3058d995...,ae0cb715407a6694fb052f4d25b9c87e97ab6ccafdb388...,151db218c9cbad4d9fa1b1196fd998a63a8314698580a6...,15689b6aebb6b896c7fdadb516c9754a34a2fcfb772dc3...,NaN,210d2693895749e26711ee890ef41c461994ce91a673aa...,False,embed,web-mobile,2020-02-15T01:53:03.000Z,...,NaN,NaN,53,vod,NaN,"Viral Seorang Siswi Dibully di Kelas, Gubernur...",News,NaN,NaN,NaN

#### Drop Unecessary Column

In [ ]:
drop_cols = ['city', 'flash_version',
             'utm_source', 'utm_medium', 'utm_campaign']

df_clean.drop(columns=drop_cols, inplace=True)
print(f"Kolom dihapus : {drop_cols}")
print(f"Sisa kolom    : {df_clean.shape[1]}")

Kolom dihapus : ['city', 'flash_version', 'utm_source', 'utm_medium', 'utm_campaign']
Sisa kolom    : 36